### ISSUE TITLE
Accessing MySQL Database remotely.

### ISSUE THREAD

**Issue by MeghashreeG** [pushkar8723/aurora#19]
First of all, we would like to thank and congratulate for a wonderful project. The design and overall flow is very user-friendly and smooth.
We are trying to integrate this SPOJ along with our web application for project purposes. In this regard, we need to connect to the MySQL Database remotely (basically, to register on Aurora SPOJ automatically, when the user registers on our application).
The main idea is to eliminate the double registration process for the user. Can you please help us on how to connect to the database remotely? We want to try the automation of the registration from our end.
We are accessing the docker application without any issues as a stand-alone instance..
Thanks in advance!

**Comment by pushkar8723** [comment]
First of all, let me reiterate that you should follow [our wiki](https://github.com/pushkar8723/aurora/wiki/Using-Docker-in-Production) for using this in production. Otherwise, a user will be able to run a program and get away with your user information.

Secondly, you can expose the MySQL port just by adding ports option in the docker-compose file. Read more about it [here](https://docs.docker.com/compose/compose-file/#ports).

**Comment by pushkar8723** [comment]
Closing the issue. Reopen if it needs further clarification.
