### ISSUE TITLE
judge closes unexpectedly

### ISSUE THREAD

**Issue by vozille** [pushkar8723/Aurora#9]
on judging a program,  except .txt files, i get RTE and terminal closes unexpectedly. if there are any compilation errors, they appear all right. I have not set up any jail or virtualenv yet. The terminal also shuts down unexpectedly when i properly close and start the judge

**Comment by pushkar8723** [comment]
There security issues if you run your judge outside jail or virtual environment and so I would recommend you to set it up. There are scripts in repo that will setup jail for you.
Still if you want to run judge without a jail / vm, you need to ensure that your system is configured properly.
For security I kill all processes started by judge user after completion. This might be the reason your terminal is closing.

### Following are the step for Debian env.

#### Steps to set up compilers and interpreters.
```
# echo "deb http://archive.ubuntu.com/ubuntu raring main universe" > "/etc/apt/sources.list"
# apt-get update
# apt-get install bf bc g++ fpc mono-gmcs openjdk-6-jdk perl php5 python python3 rhino ruby
```
Since judge depends on psmisc package and requires pymysql for db interaction, following are also required to be installed.
```
# apt-get install psmisc python3-pip
# pip3 install pymysql
```
You also need to configure perl
```
# locale-gen en_US en_US.UTF-8 hu_HU hu_HU.UTF-8
# dpkg-reconfigure locales
```

#### Steps to set up environment.

Finally create user 'judge' and change permission of directories to ensure security.
```
# chmod 700 /tmp
# useradd -m -u 8723 -s /bin/bash judge
# cd /home/judge
# curl -O https://raw.githubusercontent.com/pushkar8723/Aurora/master/Judge/judge.py
# mkdir env io_cache
# chmod 755 env
# chmod 700 io_cache
# chown judge env
# chgrp judge env
# chmod 600 judge.py
```

*Note :* You must run judge.py in /home/judge as root user.

**Comment by vozille** [comment]
I think I should have set up a virtualenv first and then played with creating user.. now I have to reinstall os :|

**Comment by pushkar8723** [comment]
There is no step that can screw up your os. What happened?

**Comment by vozille** [comment]
I was kinda stuck in a login loop and I screwed up from there, even the bios conifg is corrupted now :P .. not much experience with Linux .. will be back though in few days

**Comment by vozille** [comment]
I will set up virtual env, but first I want to run the judge, just like that.. so I created user judge, but every submission gives TLE , any reasons ?

**Comment by vozille** [comment]
silly things from my side.. anyways set up virtual env and everything work fine

**Comment by vozille** [comment]
Thanks for ur help :)
